export const ACTION_CREATE = 'CREATE_PRODUCT';
export const ACTION_EDIT = 'EDIT_PRODUCT';
export const ACTION_DELETE = 'DELETE_PRODUCT';
export const ACTION_EDIT_BUTTON = 'EDIT_BUTTON_CLICKED';
export const ACTION_INITIAL_PRODUCT = 'PRODUCT_INITIAL_STATE';
